### ISSUE TITLE
Bad response when car is not taken.

### ISSUE THREAD

**Issue by biffhero** [cookiesncream716/carbot#4]
![carbot-no-user-bug](https://user-images.githubusercontent.com/2105640/37112388-1a457ac8-21f7-11e8-8ab6-b01ed40d364f.png)

**Comment by cookiesncream716** [comment]
Fixed problem.

**Comment by biffhero** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/2105640/37125495-ca311684-2221-11e8-84e8-f628d6383b5f.png)
