### ISSUE TITLE
Request to implement new features to make app more robust.

### ISSUE THREAD

**Issue by nike1011** [cookiesncream716/carbot#5]
1. Commands should not be case sensitive.
	i.e. ‘commands list’ and “CoMMands LISt”  should give same result

2. Don’t allow user to add name or claim a car without @‘slackUserName’ to avoid any naming confusion
i.e. a) add name @cookiesncream716 
      b) @cookiesncream716 has the testCar

3. Before adding name/car if user enters any command then it should give an error that “User/car doesn’t exist. You can check all available commands using ‘commands list’”

4. Following commands are not working. (First I added name using @‘MySlackUserName’) after that I execute following commands
	I have the ___
	I took the ___
Actual result: nothing happened
Expected result: Car should claim using above command

4. User should not claim more than one car. In this situation print message that “You can’t claim another car without returning previous one”

5. If user enter any invalid command then print message that “Invalid command. You can check all available commands using ‘commands list’”

6. If car is already claimed by one user then it won’t allow another user to reclaim it. (Didn’t get a chance to verify existing behaviour)

**Comment by cookiesncream716** [comment]
1 - It has already been fixed
2 - Talk to Rob. He originally told me that he wanted people to be able to take the car that weren't in the slack channel so only allowing @username would not work.
3 - I don't think I understand what you are trying to say. It already checks to see if there is already a user or car by the same name when a user or car is added.
4 - It now recognizes the 'I took' or 'I have' but is not working properly so I will work on it more.
5 - I can add that.
6 - There is an invalid command message for any message directed @bot. If I do it for messages not directed @bot, then it will give the invalid message even if you are not wanting to give a command but just chat.
7 - Currently a user can claim a car if another person has it. Are you wanting it to say that a user can only claim an unclaimed car?

**Comment by cookiesncream716** [comment]
4 - Fixed

**Comment by nike1011** [comment]
Hi Heather,

Thank you very much for quick fix. You are an amazing coder. Please find my
response inline.

Good luck for your job search and helping out our team.

Best,
Niketan


On Thu, Mar 8, 2018 at 4:49 PM, Heather Walker <notifications@github.com>
wrote:

> 1 - It has already been fixed
> 2 - Talk to Rob. He originally told me that he wanted people to be able to
> take the car that weren't in the slack channel so only allowing @username
> would not work.
>
Niketan: If that's the case then it's fine.

> 3 - I don't think I understand what you are trying to say. It already
> checks to see if there is already a user or car by the same name when a
> user or car is added.
>
Niketan: I got it. If you do that then normal chat message will affect.
similar to # 6.

> 4 - It now recognizes the 'I took' or 'I have' but is not working properly
> so I will work on it more.
> 5 - I can add that.
>
Niketan: I talked with Rob and he mentioned user should allow to claim more
than one car but nice to have some kind of message that "You already claim
one car, are you sure you want to claim another car without returning one"

> 6 - There is an invalid command message for any message directed @bot
> <https://github.com/bot>. If I do it for messages not directed @bot
> <https://github.com/bot>, then it will give the invalid message even if
> you are not wanting to give a command but just chat.
>
Niketan: I understood your point.

> 7 - Currently a user can claim a car if another person has it. Are you
> wanting it to say that a user can only claim an unclaimed car?
>
Niketan: If one user already claim car then another user should not claim
that car.

**Comment by cookiesncream716** [comment]
5 - fixed

**Comment by cookiesncream716** [comment]
5 - I will change it back with an updated message

**Comment by cookiesncream716** [comment]
Everything is fixed.

**Comment by nike1011** [comment]
Thank you.
